; Régulateur PID de moteur — compile sur ton PC, Wokwi simule dans VS Code
[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<*>
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
