[wokwi]
version = 1
firmware = '.pio/build/esp32/firmware.bin'
elf = '.pio/build/esp32/firmware.elf'

# ESP32 web dashboard reachable from your PC: http://localhost:8182
[[net.forward]]
from = "localhost:8182"
to = "target:80"
